Logging started at 20:21:33 on 04 Mar 2013
QIIME version: 1.6.0

No qiime config provided.
No params provided.

Creating output subdirectory '/home/nbokulic/bewolf/psrotot/RDBW/multiple_assign_taxonomy/RDBW' if it doesn't already exist.
Executing commands.

# Assigning taxonomy (BLAST, E: 0.05) command 
assign_taxonomy.py -i /home/nbokulic/bewolf/psrotot/RDBW/rep_set.fna -o /home/nbokulic/bewolf/psrotot/RDBW/multiple_assign_taxonomy/RDBW/blast_0.05.tmp -e 0.05 -m blast -r /home/nbokulic/ref_seq_dbs/its_12_11_otus/rep_set/97_otus.fasta -t /home/nbokulic/ref_seq_dbs/its_12_11_otus/taxonomy/97_otu_taxonomy.txt



*** ERROR RAISED DURING STEP: Assigning taxonomy (BLAST, E: 0.05)
Command run was:
 assign_taxonomy.py -i /home/nbokulic/bewolf/psrotot/RDBW/rep_set.fna -o /home/nbokulic/bewolf/psrotot/RDBW/multiple_assign_taxonomy/RDBW/blast_0.05.tmp -e 0.05 -m blast -r /home/nbokulic/ref_seq_dbs/its_12_11_otus/rep_set/97_otus.fasta -t /home/nbokulic/ref_seq_dbs/its_12_11_otus/taxonomy/97_otu_taxonomy.txt
Command returned exit status: 1
Stdout:

Stderr
Traceback (most recent call last):
  File "/share/apps/qiime-1.6.0/scripts/assign_taxonomy.py", line 305, in <module>
    main()
  File "/share/apps/qiime-1.6.0/scripts/assign_taxonomy.py", line 283, in main
    result_path=temp_result_path,log_path=log_path)
  File "/share/apps/qiime-1.6.0/lib/qiime/assign_taxonomy.py", line 164, in __call__
    build_blast_db_from_fasta_path(reference_seqs_path)
  File "/share/apps/python-2.7.3/lib/python2.7/site-packages/cogent/app/formatdb.py", line 119, in build_blast_db_from_fasta_path
    app_result = fdb(fasta_path)
  File "/share/apps/python-2.7.3/lib/python2.7/site-packages/cogent/app/util.py", line 251, in __call__
    open(errfile).read())
cogent.app.util.ApplicationError: Unacceptable application exit status: 9
Command:
cd "/home/nbokulic/ref_seq_dbs/its_12_11_otus/rep_set/"; formatdb -l "97_otus.fasta.log" -o T -n "97_otus.fasta" -i "97_otus.fasta" -p F > "/dev/null" 2> "/dev/null"
StdOut:

StdErr:




Logging stopped at 20:21:36 on 04 Mar 2013
